version = 1


[install]
gum.pkg-path = "gum"

[vars]
BUILDTIME_NIXPKGS_URL="github:NixOS/nixpkgs/nixpkgs-unstable"

[build]
neovim-cp.description="Neovim with the copilot.vim plugin included"
neovim-cp.command = '''
  mkdir -p $out/bin
  cp ${myneovim}/bin/nvim $out/bin/nvim
'''

